# Generated by Django 3.1.1 on 2020-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_unit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='remarks',
        ),
        migrations.AddField(
            model_name='area',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='city',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='country',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='room',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Remarks'),
        ),
    ]
