# Generated by Django 3.1.1 on 2020-09-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20200924_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='furniture_image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
